-- Check Missing Gyms in Database
-- Expected total: 211 gyms
-- Generated: 2025-11-15T23:19:11.131030

-- ============================================================================
-- QUERY 1: Count gyms by city
-- ============================================================================
SELECT
  c.name as city_name,
  COUNT(g.id) as gym_count
FROM cities c
LEFT JOIN gyms g ON g.city_id = c.id
GROUP BY c.id, c.name
ORDER BY c.name;

-- ============================================================================
-- QUERY 2: Find missing gyms by city
-- ============================================================================

-- Check Limassol (50 expected)
SELECT 'Limassol' as city, slug, name, 'MISSING' as status
FROM (VALUES
  ('ballet-school-pilates-studio-monika-perikleous', 'Ballet School & Pilates Studio Monika Perikleous'),
  ('vinyasa-yoga-studio-limassol', 'Vinyasa Yoga Studio Limassol'),
  ('piero-judo-academy', 'Piero Judo Academy'),
  ('limassol-fitness', 'Limassol Fitness'),
  ('soul-vibe-space', 'Soul Vibe Space'),
  ('endless-flow', 'Endless Flow'),
  ('nicos-solomonides-indoor-arena-ael', 'Nicos Solomonides Indoor Arena Ael'),
  ('no75space', 'No75Space'),
  ('checkmat-limassol', 'Checkmat Limassol'),
  ('mma-school-the-cage', 'Mma School The Cage'),
  ('catman-olympic-boxing-academy-c7m', 'Catman Olympic Boxing Academy C7M'),
  ('gymania-personal-trainer', 'Gymania Personal Trainer'),
  ('target-boxing-club', 'Target Boxing Club'),
  ('kpk-performance-rehabilitation-center', 'Kpk Performance & Rehabilitation Center'),
  ('lumpinee-gym-muay-thai-muay-boran-personal-training-fighting-club-limassol-cyprus', 'Lumpinee Gym - Muay Thai - Muay Boran - Personal Training - Fighting Club - Limassol - Cyprus'),
  ('peak-condition-cyprus', 'Peak Condition Cyprus'),
  ('body-advance-personal-training-studio', 'Body Advance Personal Training Studio'),
  ('studio-iv-360-pilates-beyond', 'Studio Iv 360 Pilates & Beyond'),
  ('contrology-studio', 'Contrology Studio'),
  ('un1t', 'Un1T'),
  ('kinetic-fitness-studio', 'Kinetic Fitness Studio'),
  ('fitness-lab', 'Fitness Lab'),
  ('dainas-planet-fitness', 'Dainas Planet Fitness'),
  ('kinetic-pilates-studio', 'Kinetic Pilates Studio'),
  ('savs-gym', 'SavS Gym'),
  ('combat-fitness', 'Combat & Fitness'),
  ('limassol-sporting-center', 'Limassol Sporting Center'),
  ('bodyfitness-gym-center', 'Bodyfitness Gym Center'),
  ('asfperformance-limassol-cyprus-gym-taekwondo', 'Asf&Performance Limassol Cyprus Gym Taekwondo '),
  ('crossfit-limassol', 'Crossfit Limassol'),
  ('iron-fitness', 'Iron Fitness'),
  ('ara-gym-xl', 'Ara Gym Xl'),
  ('team-rogue-forge', 'Team Rogue Forge'),
  ('reload-fitness-studio', 'Reload Fitness Studio'),
  ('muscle-factory-24-hours', 'Muscle Factory 24 Hours'),
  ('grind-fitness', 'Grind Fitness'),
  ('vip-gym', 'Vip-Gym'),
  ('anaplasis-gym-fitness-center-limassol', 'Anaplasis Gym Fitness Center Limassol'),
  ('gymania-fitness-club', 'Gymania Fitness Club'),
  ('champ-boxing-academy', 'Champ Boxing Academy'),
  ('her-gym-limassol', 'Her Gym Limassol'),
  ('dreamchasers-fitness-studio', 'Dreamchasers Fitness Studio'),
  ('5-rounds-mma-limassol', '5 Rounds Mma Limassol'),
  ('slim-and-smart-fitness-studio', 'Slim And Smart Fitness Studio'),
  ('r-evolution-of-gym', 'R-Evolution Of Gym'),
  ('progress-gym', 'Progress Gym'),
  ('bodysense-healthfitness-centre', 'Bodysense Health&Fitness Centre'),
  ('the-fitzone-by-kondylis', 'The Fitzone By Kondylis'),
  ('kalopedi-gym', 'Kalopedi Gym'),
  ('raw-calisthenics-academy', 'Raw Calisthenics Academy')
) AS expected(slug, name)
WHERE slug NOT IN (
  SELECT slug FROM gyms 
  WHERE city_id = (SELECT id FROM cities WHERE name = 'Limassol')
);

-- Check Nicosia (71 expected)
SELECT 'Nicosia' as city, slug, name, 'MISSING' as status
FROM (VALUES
  ('the-yogi-turtle', 'The Yogi Turtle'),
  ('e-motion-dance-health-studio-viantos', 'E-Motion Dance & Health Studio - Viantos'),
  ('riforma-pilates-studio', 'Riforma Pilates Studio'),
  ('renzo-gracie-nicosia-brazilian-jiu-jitsu', 'Renzo Gracie Nicosia - Brazilian Jiu Jitsu'),
  ('filippos-taekwondo-itf-nicosia', 'Filippos Taekwondo Itf Nicosia'),
  ('bhava', 'Bhava'),
  ('in2motion-fitness-studio', 'In2Motion Fitness Studio'),
  ('cocoon-wellness-centre', 'Cocoon Wellness Centre'),
  ('for-me-clinical-physio-pilates-studio', 'For Me Clinical Physio Pilates Studio'),
  ('uppercut-team-cyprus-boxing-kickboxing-school-in-strovolos-nicosia', 'Uppercut Team Cyprus Boxing - Kickboxing School In Strovolos Nicosia'),
  ('güralpfit', 'Güralpfit'),
  ('hellenic-bank-masters-tennis-academy', 'Hellenic Bank Masters Tennis Academy'),
  ('aurora-pilates-studio', 'Aurora Pilates Studio'),
  ('fit-2-the-point', 'Fit 2 The Point'),
  ('ananda-yoga-studio', 'Ananda Yoga Studio'),
  ('calisthenics-area', 'Calisthenics Area'),
  ('intense-fitness-physio-centre', 'Intense Fitness & Physio Centre'),
  ('ryltoday', 'Ryltoday'),
  ('gymac-boutique-fitness-personal-training', 'Gymac Boutique Fitness & Personal Training'),
  ('elite-body-management', 'Elite Body Management'),
  ('global-vale-tudo-combat-sports-academy', 'Global Vale Tudo - Combat Sports Academy'),
  ('bobi-boxing-club', 'Bobi Boxing Club'),
  ('ambitus-fitness', 'Ambitus Fitness'),
  ('karma-studio', 'Karma Studio'),
  ('tcycle', 'Tcycle'),
  ('bianco-poolbar-lounge', 'Bianco Pool&Bar Lounge'),
  ('kamae-fitness', 'Kamae Fitness'),
  ('university-of-nicosia-ufit-fitness-centre', 'University Of Nicosia - Ufit Fitness Centre'),
  ('energea-fitness-studio-ems-training-pilates-reformer', 'Energea Fitness Studio - Ems Training & Pilates Reformer'),
  ('hupex-fitness', 'Hupex Fitness'),
  ('supernatural-gym', 'Supernatural Gym'),
  ('sana-hiltonia-health-fitness-centre', 'Sana Hiltonia Health & Fitness Centre'),
  ('nicosia-gymnastic-center', 'Nicosia Gymnastic Center'),
  ('rise-fitness-club', 'Rise Fitness Club'),
  ('en-somati-lifestyle-gym-personal-training-mma-academy', 'En Somati - Lifestyle Gym Personal Training Mma Academy'),
  ('oxygen-gym', 'Oxygen Gym'),
  ('momentum-fitness-wellness', 'Momentum Fitness & Wellness'),
  ('100-boxing-fitness-gym', '100 Boxing & Fitness Gym'),
  ('science-fit', 'Science Fit'),
  ('new-body-gym', 'New Body Gym'),
  ('maxx-fitness', 'Maxx Fitness'),
  ('fitness-factory', 'Fitness Factory'),
  ('fuelhouse-boutique-fitness-club', 'Fuelhouse Boutique Fitness Club'),
  ('real-fit', 'Real Fit'),
  ('squad-by-xfit', 'Squad By XFit'),
  ('regenesis-gym', 'Regenesis Gym'),
  ('fitensity-training-club', 'Fitensity Training Club'),
  ('komanetsi-fitness-center', 'Komanetsi Fitness Center'),
  ('destination-fitness', 'Destination Fitness'),
  ('μολων-λαβε-gym', 'Μολων Λαβε Gym'),
  ('new-life-health-centre-nicosia-gym', 'New Life Health Centre - Nicosia Gym'),
  ('curves-aglantzias', 'Curves Aglantzias'),
  ('underground-force-gym', 'Underground Force Gym'),
  ('gabriel-fitness-boxing-gym', 'Gabriel Fitness & Boxing Gym'),
  ('fortius-boxing-academy', 'Fortius Boxing Academy'),
  ('class-one-fitness', 'Class One Fitness'),
  ('body-explosion-fitness-place', 'Body Explosion Fitness Place'),
  ('φόρμα-fitness-studio', 'Φόρμα Fitness Studio'),
  ('mr-cyprus-gym', 'Mr Cyprus Gym'),
  ('infinity-fitness-hall', 'Infinity Fitness Hall'),
  ('eurogym', 'Eurogym'),
  ('at4fitness-gym', 'At4Fitness Gym'),
  ('home-gym', 'Home Gym'),
  ('old-town-fitness-studio', 'Old Town Fitness Studio'),
  ('motus-boutique-gym', 'Motus Boutique Gym'),
  ('be-different-gym-fitness-club', 'Be Different Gym & Fitness Club'),
  ('olympus-gym', 'Olympus Gym'),
  ('ibody-fitness-and-dance-studio-ltd', 'Ibody Fitness And Dance Studio Ltd'),
  ('profit-center-nicosia', 'ProFit Center Nicosia'),
  ('figure8gym', 'Figure8Gym'),
  ('urban-boutique-gym', 'Urban Boutique Gym')
) AS expected(slug, name)
WHERE slug NOT IN (
  SELECT slug FROM gyms 
  WHERE city_id = (SELECT id FROM cities WHERE name = 'Nicosia')
);

-- Check Larnaca (43 expected)
SELECT 'Larnaca' as city, slug, name, 'MISSING' as status
FROM (VALUES
  ('foxteam-taekwondo-larnaca', 'Foxteam Taekwondo Larnaca'),
  ('wellnest-pilates-studio', 'Wellnest Pilates Studio'),
  ('live-studio-mike', 'Live Studio Mike'),
  ('eplarkou-pilates', 'Eplarkou Pilates'),
  ('a-studio-pilates-fitness', 'A Studio Pilates & Fitness'),
  ('moksha-fitlab', 'Moksha Fitlab'),
  ('alignment-pilates-studio', 'Alignment Pilates Studio'),
  ('bareknuckle-crossfit', 'Bareknuckle Crossfit'),
  ('gymland-ματσαγγίδης', 'Gymland Ματσαγγίδης'),
  ('vital-strength-training', 'Vital Strength Training'),
  ('olympia-movement', 'Olympia Movement'),
  ('andreas-zachariou-holistic-sport-clinic', 'Andreas Zachariou Holistic Sport Clinic'),
  ('gymnastics-hall-larnaca', 'Gymnastics Hall Larnaca'),
  ('c-larnaca-red-box', 'C Larnaca Red Box'),
  ('outdoor-calisthenics-workout-spot', 'Outdoor Calisthenics Workout Spot'),
  ('cyprus-top-team-cttmma-kickboxing-muaythaibjj-fitness-gym', 'Cyprus Top Team CttMma Kickboxing MuaythaiBjj Fitness Gym'),
  ('elit3-fitness-nutrition', 'Elit3 Fitness & Nutrition'),
  ('the-big-gym-of-functional-training-and-yoga', 'The Big Gym Of Functional Training And Yoga'),
  ('diaplasis-premium-fitness', 'Diaplasis Premium Fitness'),
  ('samtsihara-fight-system-global-academy', 'Samtsihara Fight System Global Academy'),
  ('profit-center', 'ProFit Center'),
  ('onyx-boutique-gym', 'Onyx Boutique Gym'),
  ('the-big-gym-of-muay-thai-and-fitness-larnaca', 'The Big Gym Of Muay Thai And Fitness Larnaca'),
  ('arise-active', 'Arise Active'),
  ('legacy-chris-antoniou-training', 'Legacy - Chris Antoniou Training'),
  ('86seven-fitness-boutique', '86Seven Fitness Boutique'),
  ('acceptus-gym', 'Acceptus Gym'),
  ('ironsky-fitness-group-personal-training-in-larnaca', 'Ironsky Fitness  Group & Personal Training In Larnaca'),
  ('reflex-gym-larnaca', 'Reflex Gym Larnaca'),
  ('getfitgym-elite', 'Getfitgym Elite'),
  ('trojans-gym', 'Trojans Gym'),
  ('athletic-fitness-center', 'Athletic Fitness Center'),
  ('boxing-muscle-personal-boxing-fitness-training-larnaca', 'Boxing Muscle Personal Boxing & Fitness Training Larnaca'),
  ('expose-fitness-by-andreas-cosma', 'Expose Fitness By Andreas Cosma'),
  ('fivestar-sportcenter', 'Fivestar Sportcenter'),
  ('temple-fitness', 'Temple Fitness'),
  ('delta-fitness-studio', 'Delta Fitness Studio'),
  ('rack-gym-ltd', 'Rack Gym Ltd'),
  ('totalfit', 'Totalfit'),
  ('aquagym', 'Aquagym'),
  ('twp-train-with-passion', 'Twp-Train With Passion'),
  ('its-time-fitness-center', 'ItS Time Fitness Center'),
  ('body-control-fitness-centre', 'Body Control Fitness Centre')
) AS expected(slug, name)
WHERE slug NOT IN (
  SELECT slug FROM gyms 
  WHERE city_id = (SELECT id FROM cities WHERE name = 'Larnaca')
);

-- Check Paphos (34 expected)
SELECT 'Paphos' as city, slug, name, 'MISSING' as status
FROM (VALUES
  ('the-hood-fitness-house', 'The Hood Fitness House'),
  ('kings-brazilian-jiu-jitsu', 'Kings Brazilian Jiu Jitsu'),
  ('pilates-reformer-studio', 'Pilates Reformer Studio'),
  ('zr-jiu-jitsu', 'Zr Jiu Jitsu'),
  ('soulutionpilatesmore', 'Soulutionpilates&More'),
  ('team-akopian', 'Team Akopian'),
  ('furious-fighters', 'Furious Fighters'),
  ('aa-power-mode', 'Aa Power Mode'),
  ('akba-health-care-center', 'Akba Health Care Center'),
  ('personal-trainer-paphos-kissonerga-peyia', 'Personal Trainer - Paphos Kissonerga & Peyia'),
  ('dinamico-personal-training-center', 'Dinamico Personal Training Center'),
  ('mg-fitness-club', 'Mg Fitness Club'),
  ('johnnys-personal-training', 'JohnnyS Personal Training'),
  ('aesthetics-fitness-club', 'Aesthetics Fitness Club'),
  ('paphos-professional-boxing-gym', 'Paphos Professional Boxing Gym'),
  ('poseidonio-health-spa-and-fitness-center', 'Poseidonio Health Spa And Fitness Center'),
  ('municipality-gym', 'Municipality Gym'),
  ('aidinidis-fight-club', 'Aidinidis Fight Club'),
  ('johnnys-gym', 'JohnnyS Gym'),
  ('fiit-paphos-training-room', 'Fiit Paphos Training Room'),
  ('nayara-fonseca-aerial', 'Nayara Fonseca Aerial'),
  ('vo2-fitness-center-personal-training-studio', 'Vo2 Fitness Center - Personal Training Studio'),
  ('star-fitness-gym-paphos-cyprus', 'Star Fitness Gym Paphos Cyprus'),
  ('vigour-studio-gym', 'Vigour Studio Gym'),
  ('aesthetics-fitness-club-gold', 'Aesthetics Fitness Club Gold'),
  ('bodyart-fitnessgym', 'Bodyart Fitnessgym'),
  ('energy-fitness-gym', 'Energy Fitness Gym'),
  ('hardcoretraining-gym-paphos', 'Hardcoretraining Gym Paphos'),
  ('paphos-thai-boxing-mma-fight-club-old-style-muay-thai', 'Paphos Thai Boxing & Mma Fight Club Old Style Muay Thai'),
  ('g-fitness', 'G Fitness'),
  ('west-34-elite-fitness-club', 'West 34 Elite Fitness Club'),
  ('forma-personal-training-studio-gym', 'Forma Personal Training Studio Gym'),
  ('gymnastika-fitness-center', 'Gymnastika Fitness Center'),
  ('hyper-fitness-club', 'Hyper Fitness Club')
) AS expected(slug, name)
WHERE slug NOT IN (
  SELECT slug FROM gyms 
  WHERE city_id = (SELECT id FROM cities WHERE name = 'Paphos')
);

-- Check Ayia Napa (6 expected)
SELECT 'Ayia Napa' as city, slug, name, 'MISSING' as status
FROM (VALUES
  ('sunwing-fitness-center', 'Sunwing Fitness Center'),
  ('overall-magic-fitness-center', 'Overall Magic Fitness Center'),
  ('datiki-diet', 'Datiki Diet'),
  ('return-rehabilitation-fitness-recovery-centre', 'Return Rehabilitation & Fitness Recovery Centre'),
  ('world-gym-ayia-napa', 'World Gym Ayia Napa'),
  ('bad-dog-bjj-brazilian-jiu-jitsu-training-club-nickbjj', 'Bad Dog Bjj  Brazilian Jiu-Jitsu Training Club  Nickbjj')
) AS expected(slug, name)
WHERE slug NOT IN (
  SELECT slug FROM gyms 
  WHERE city_id = (SELECT id FROM cities WHERE name = 'Ayia Napa')
);

-- Check Protaras (7 expected)
SELECT 'Protaras' as city, slug, name, 'MISSING' as status
FROM (VALUES
  ('body-shape-gym', 'Body Shape Gym'),
  ('bodyart-fitness-center', 'Bodyart Fitness Center'),
  ('mythical-performance', 'Mythical Performance'),
  ('demari-wellness-and-spa', 'Demari Wellness And Spa'),
  ('limitlessxposed', 'Limitlessxposed'),
  ('sacred-roots-yoga-massage', 'Sacred Roots Yoga & Massage'),
  ('calisthenicsworkout4allcy', 'Calisthenicsworkout4Allcy')
) AS expected(slug, name)
WHERE slug NOT IN (
  SELECT slug FROM gyms 
  WHERE city_id = (SELECT id FROM cities WHERE name = 'Protaras')
);

-- ============================================================================
-- QUERY 3: Comprehensive check - All expected vs actual
-- ============================================================================
WITH expected_gyms AS (
  SELECT * FROM (VALUES
    ('Limassol', 'ballet-school-pilates-studio-monika-perikleous', 'Ballet School & Pilates Studio Monika Perikleous'),
    ('Limassol', 'vinyasa-yoga-studio-limassol', 'Vinyasa Yoga Studio Limassol'),
    ('Limassol', 'piero-judo-academy', 'Piero Judo Academy'),
    ('Limassol', 'limassol-fitness', 'Limassol Fitness'),
    ('Limassol', 'soul-vibe-space', 'Soul Vibe Space'),
    ('Limassol', 'endless-flow', 'Endless Flow'),
    ('Limassol', 'nicos-solomonides-indoor-arena-ael', 'Nicos Solomonides Indoor Arena Ael'),
    ('Limassol', 'no75space', 'No75Space'),
    ('Limassol', 'checkmat-limassol', 'Checkmat Limassol'),
    ('Limassol', 'mma-school-the-cage', 'Mma School The Cage'),
    ('Limassol', 'catman-olympic-boxing-academy-c7m', 'Catman Olympic Boxing Academy C7M'),
    ('Limassol', 'gymania-personal-trainer', 'Gymania Personal Trainer'),
    ('Limassol', 'target-boxing-club', 'Target Boxing Club'),
    ('Limassol', 'kpk-performance-rehabilitation-center', 'Kpk Performance & Rehabilitation Center'),
    ('Limassol', 'lumpinee-gym-muay-thai-muay-boran-personal-training-fighting-club-limassol-cyprus', 'Lumpinee Gym - Muay Thai - Muay Boran - Personal Training - Fighting Club - Limassol - Cyprus'),
    ('Limassol', 'peak-condition-cyprus', 'Peak Condition Cyprus'),
    ('Limassol', 'body-advance-personal-training-studio', 'Body Advance Personal Training Studio'),
    ('Limassol', 'studio-iv-360-pilates-beyond', 'Studio Iv 360 Pilates & Beyond'),
    ('Limassol', 'contrology-studio', 'Contrology Studio'),
    ('Limassol', 'un1t', 'Un1T'),
    ('Limassol', 'kinetic-fitness-studio', 'Kinetic Fitness Studio'),
    ('Limassol', 'fitness-lab', 'Fitness Lab'),
    ('Limassol', 'dainas-planet-fitness', 'Dainas Planet Fitness'),
    ('Limassol', 'kinetic-pilates-studio', 'Kinetic Pilates Studio'),
    ('Limassol', 'savs-gym', 'SavS Gym'),
    ('Limassol', 'combat-fitness', 'Combat & Fitness'),
    ('Limassol', 'limassol-sporting-center', 'Limassol Sporting Center'),
    ('Limassol', 'bodyfitness-gym-center', 'Bodyfitness Gym Center'),
    ('Limassol', 'asfperformance-limassol-cyprus-gym-taekwondo', 'Asf&Performance Limassol Cyprus Gym Taekwondo '),
    ('Limassol', 'crossfit-limassol', 'Crossfit Limassol'),
    ('Limassol', 'iron-fitness', 'Iron Fitness'),
    ('Limassol', 'ara-gym-xl', 'Ara Gym Xl'),
    ('Limassol', 'team-rogue-forge', 'Team Rogue Forge'),
    ('Limassol', 'reload-fitness-studio', 'Reload Fitness Studio'),
    ('Limassol', 'muscle-factory-24-hours', 'Muscle Factory 24 Hours'),
    ('Limassol', 'grind-fitness', 'Grind Fitness'),
    ('Limassol', 'vip-gym', 'Vip-Gym'),
    ('Limassol', 'anaplasis-gym-fitness-center-limassol', 'Anaplasis Gym Fitness Center Limassol'),
    ('Limassol', 'gymania-fitness-club', 'Gymania Fitness Club'),
    ('Limassol', 'champ-boxing-academy', 'Champ Boxing Academy'),
    ('Limassol', 'her-gym-limassol', 'Her Gym Limassol'),
    ('Limassol', 'dreamchasers-fitness-studio', 'Dreamchasers Fitness Studio'),
    ('Limassol', '5-rounds-mma-limassol', '5 Rounds Mma Limassol'),
    ('Limassol', 'slim-and-smart-fitness-studio', 'Slim And Smart Fitness Studio'),
    ('Limassol', 'r-evolution-of-gym', 'R-Evolution Of Gym'),
    ('Limassol', 'progress-gym', 'Progress Gym'),
    ('Limassol', 'bodysense-healthfitness-centre', 'Bodysense Health&Fitness Centre'),
    ('Limassol', 'the-fitzone-by-kondylis', 'The Fitzone By Kondylis'),
    ('Limassol', 'kalopedi-gym', 'Kalopedi Gym'),
    ('Limassol', 'raw-calisthenics-academy', 'Raw Calisthenics Academy'),
    ('Nicosia', 'the-yogi-turtle', 'The Yogi Turtle'),
    ('Nicosia', 'e-motion-dance-health-studio-viantos', 'E-Motion Dance & Health Studio - Viantos'),
    ('Nicosia', 'riforma-pilates-studio', 'Riforma Pilates Studio'),
    ('Nicosia', 'renzo-gracie-nicosia-brazilian-jiu-jitsu', 'Renzo Gracie Nicosia - Brazilian Jiu Jitsu'),
    ('Nicosia', 'filippos-taekwondo-itf-nicosia', 'Filippos Taekwondo Itf Nicosia'),
    ('Nicosia', 'bhava', 'Bhava'),
    ('Nicosia', 'in2motion-fitness-studio', 'In2Motion Fitness Studio'),
    ('Nicosia', 'cocoon-wellness-centre', 'Cocoon Wellness Centre'),
    ('Nicosia', 'for-me-clinical-physio-pilates-studio', 'For Me Clinical Physio Pilates Studio'),
    ('Nicosia', 'uppercut-team-cyprus-boxing-kickboxing-school-in-strovolos-nicosia', 'Uppercut Team Cyprus Boxing - Kickboxing School In Strovolos Nicosia'),
    ('Nicosia', 'güralpfit', 'Güralpfit'),
    ('Nicosia', 'hellenic-bank-masters-tennis-academy', 'Hellenic Bank Masters Tennis Academy'),
    ('Nicosia', 'aurora-pilates-studio', 'Aurora Pilates Studio'),
    ('Nicosia', 'fit-2-the-point', 'Fit 2 The Point'),
    ('Nicosia', 'ananda-yoga-studio', 'Ananda Yoga Studio'),
    ('Nicosia', 'calisthenics-area', 'Calisthenics Area'),
    ('Nicosia', 'intense-fitness-physio-centre', 'Intense Fitness & Physio Centre'),
    ('Nicosia', 'ryltoday', 'Ryltoday'),
    ('Nicosia', 'gymac-boutique-fitness-personal-training', 'Gymac Boutique Fitness & Personal Training'),
    ('Nicosia', 'elite-body-management', 'Elite Body Management'),
    ('Nicosia', 'global-vale-tudo-combat-sports-academy', 'Global Vale Tudo - Combat Sports Academy'),
    ('Nicosia', 'bobi-boxing-club', 'Bobi Boxing Club'),
    ('Nicosia', 'ambitus-fitness', 'Ambitus Fitness'),
    ('Nicosia', 'karma-studio', 'Karma Studio'),
    ('Nicosia', 'tcycle', 'Tcycle'),
    ('Nicosia', 'bianco-poolbar-lounge', 'Bianco Pool&Bar Lounge'),
    ('Nicosia', 'kamae-fitness', 'Kamae Fitness'),
    ('Nicosia', 'university-of-nicosia-ufit-fitness-centre', 'University Of Nicosia - Ufit Fitness Centre'),
    ('Nicosia', 'energea-fitness-studio-ems-training-pilates-reformer', 'Energea Fitness Studio - Ems Training & Pilates Reformer'),
    ('Nicosia', 'hupex-fitness', 'Hupex Fitness'),
    ('Nicosia', 'supernatural-gym', 'Supernatural Gym'),
    ('Nicosia', 'sana-hiltonia-health-fitness-centre', 'Sana Hiltonia Health & Fitness Centre'),
    ('Nicosia', 'nicosia-gymnastic-center', 'Nicosia Gymnastic Center'),
    ('Nicosia', 'rise-fitness-club', 'Rise Fitness Club'),
    ('Nicosia', 'en-somati-lifestyle-gym-personal-training-mma-academy', 'En Somati - Lifestyle Gym Personal Training Mma Academy'),
    ('Nicosia', 'oxygen-gym', 'Oxygen Gym'),
    ('Nicosia', 'momentum-fitness-wellness', 'Momentum Fitness & Wellness'),
    ('Nicosia', '100-boxing-fitness-gym', '100 Boxing & Fitness Gym'),
    ('Nicosia', 'science-fit', 'Science Fit'),
    ('Nicosia', 'new-body-gym', 'New Body Gym'),
    ('Nicosia', 'maxx-fitness', 'Maxx Fitness'),
    ('Nicosia', 'fitness-factory', 'Fitness Factory'),
    ('Nicosia', 'fuelhouse-boutique-fitness-club', 'Fuelhouse Boutique Fitness Club'),
    ('Nicosia', 'real-fit', 'Real Fit'),
    ('Nicosia', 'squad-by-xfit', 'Squad By XFit'),
    ('Nicosia', 'regenesis-gym', 'Regenesis Gym'),
    ('Nicosia', 'fitensity-training-club', 'Fitensity Training Club'),
    ('Nicosia', 'komanetsi-fitness-center', 'Komanetsi Fitness Center'),
    ('Nicosia', 'destination-fitness', 'Destination Fitness'),
    ('Nicosia', 'μολων-λαβε-gym', 'Μολων Λαβε Gym'),
    ('Nicosia', 'new-life-health-centre-nicosia-gym', 'New Life Health Centre - Nicosia Gym'),
    ('Nicosia', 'curves-aglantzias', 'Curves Aglantzias'),
    ('Nicosia', 'underground-force-gym', 'Underground Force Gym'),
    ('Nicosia', 'gabriel-fitness-boxing-gym', 'Gabriel Fitness & Boxing Gym'),
    ('Nicosia', 'fortius-boxing-academy', 'Fortius Boxing Academy'),
    ('Nicosia', 'class-one-fitness', 'Class One Fitness'),
    ('Nicosia', 'body-explosion-fitness-place', 'Body Explosion Fitness Place'),
    ('Nicosia', 'φόρμα-fitness-studio', 'Φόρμα Fitness Studio'),
    ('Nicosia', 'mr-cyprus-gym', 'Mr Cyprus Gym'),
    ('Nicosia', 'infinity-fitness-hall', 'Infinity Fitness Hall'),
    ('Nicosia', 'eurogym', 'Eurogym'),
    ('Nicosia', 'at4fitness-gym', 'At4Fitness Gym'),
    ('Nicosia', 'home-gym', 'Home Gym'),
    ('Nicosia', 'old-town-fitness-studio', 'Old Town Fitness Studio'),
    ('Nicosia', 'motus-boutique-gym', 'Motus Boutique Gym'),
    ('Nicosia', 'be-different-gym-fitness-club', 'Be Different Gym & Fitness Club'),
    ('Nicosia', 'olympus-gym', 'Olympus Gym'),
    ('Nicosia', 'ibody-fitness-and-dance-studio-ltd', 'Ibody Fitness And Dance Studio Ltd'),
    ('Nicosia', 'profit-center-nicosia', 'ProFit Center Nicosia'),
    ('Nicosia', 'figure8gym', 'Figure8Gym'),
    ('Nicosia', 'urban-boutique-gym', 'Urban Boutique Gym'),
    ('Larnaca', 'foxteam-taekwondo-larnaca', 'Foxteam Taekwondo Larnaca'),
    ('Larnaca', 'wellnest-pilates-studio', 'Wellnest Pilates Studio'),
    ('Larnaca', 'live-studio-mike', 'Live Studio Mike'),
    ('Larnaca', 'eplarkou-pilates', 'Eplarkou Pilates'),
    ('Larnaca', 'a-studio-pilates-fitness', 'A Studio Pilates & Fitness'),
    ('Larnaca', 'moksha-fitlab', 'Moksha Fitlab'),
    ('Larnaca', 'alignment-pilates-studio', 'Alignment Pilates Studio'),
    ('Larnaca', 'bareknuckle-crossfit', 'Bareknuckle Crossfit'),
    ('Larnaca', 'gymland-ματσαγγίδης', 'Gymland Ματσαγγίδης'),
    ('Larnaca', 'vital-strength-training', 'Vital Strength Training'),
    ('Larnaca', 'olympia-movement', 'Olympia Movement'),
    ('Larnaca', 'andreas-zachariou-holistic-sport-clinic', 'Andreas Zachariou Holistic Sport Clinic'),
    ('Larnaca', 'gymnastics-hall-larnaca', 'Gymnastics Hall Larnaca'),
    ('Larnaca', 'c-larnaca-red-box', 'C Larnaca Red Box'),
    ('Larnaca', 'outdoor-calisthenics-workout-spot', 'Outdoor Calisthenics Workout Spot'),
    ('Larnaca', 'cyprus-top-team-cttmma-kickboxing-muaythaibjj-fitness-gym', 'Cyprus Top Team CttMma Kickboxing MuaythaiBjj Fitness Gym'),
    ('Larnaca', 'elit3-fitness-nutrition', 'Elit3 Fitness & Nutrition'),
    ('Larnaca', 'the-big-gym-of-functional-training-and-yoga', 'The Big Gym Of Functional Training And Yoga'),
    ('Larnaca', 'diaplasis-premium-fitness', 'Diaplasis Premium Fitness'),
    ('Larnaca', 'samtsihara-fight-system-global-academy', 'Samtsihara Fight System Global Academy'),
    ('Larnaca', 'profit-center', 'ProFit Center'),
    ('Larnaca', 'onyx-boutique-gym', 'Onyx Boutique Gym'),
    ('Larnaca', 'the-big-gym-of-muay-thai-and-fitness-larnaca', 'The Big Gym Of Muay Thai And Fitness Larnaca'),
    ('Larnaca', 'arise-active', 'Arise Active'),
    ('Larnaca', 'legacy-chris-antoniou-training', 'Legacy - Chris Antoniou Training'),
    ('Larnaca', '86seven-fitness-boutique', '86Seven Fitness Boutique'),
    ('Larnaca', 'acceptus-gym', 'Acceptus Gym'),
    ('Larnaca', 'ironsky-fitness-group-personal-training-in-larnaca', 'Ironsky Fitness  Group & Personal Training In Larnaca'),
    ('Larnaca', 'reflex-gym-larnaca', 'Reflex Gym Larnaca'),
    ('Larnaca', 'getfitgym-elite', 'Getfitgym Elite'),
    ('Larnaca', 'trojans-gym', 'Trojans Gym'),
    ('Larnaca', 'athletic-fitness-center', 'Athletic Fitness Center'),
    ('Larnaca', 'boxing-muscle-personal-boxing-fitness-training-larnaca', 'Boxing Muscle Personal Boxing & Fitness Training Larnaca'),
    ('Larnaca', 'expose-fitness-by-andreas-cosma', 'Expose Fitness By Andreas Cosma'),
    ('Larnaca', 'fivestar-sportcenter', 'Fivestar Sportcenter'),
    ('Larnaca', 'temple-fitness', 'Temple Fitness'),
    ('Larnaca', 'delta-fitness-studio', 'Delta Fitness Studio'),
    ('Larnaca', 'rack-gym-ltd', 'Rack Gym Ltd'),
    ('Larnaca', 'totalfit', 'Totalfit'),
    ('Larnaca', 'aquagym', 'Aquagym'),
    ('Larnaca', 'twp-train-with-passion', 'Twp-Train With Passion'),
    ('Larnaca', 'its-time-fitness-center', 'ItS Time Fitness Center'),
    ('Larnaca', 'body-control-fitness-centre', 'Body Control Fitness Centre'),
    ('Paphos', 'the-hood-fitness-house', 'The Hood Fitness House'),
    ('Paphos', 'kings-brazilian-jiu-jitsu', 'Kings Brazilian Jiu Jitsu'),
    ('Paphos', 'pilates-reformer-studio', 'Pilates Reformer Studio'),
    ('Paphos', 'zr-jiu-jitsu', 'Zr Jiu Jitsu'),
    ('Paphos', 'soulutionpilatesmore', 'Soulutionpilates&More'),
    ('Paphos', 'team-akopian', 'Team Akopian'),
    ('Paphos', 'furious-fighters', 'Furious Fighters'),
    ('Paphos', 'aa-power-mode', 'Aa Power Mode'),
    ('Paphos', 'akba-health-care-center', 'Akba Health Care Center'),
    ('Paphos', 'personal-trainer-paphos-kissonerga-peyia', 'Personal Trainer - Paphos Kissonerga & Peyia'),
    ('Paphos', 'dinamico-personal-training-center', 'Dinamico Personal Training Center'),
    ('Paphos', 'mg-fitness-club', 'Mg Fitness Club'),
    ('Paphos', 'johnnys-personal-training', 'JohnnyS Personal Training'),
    ('Paphos', 'aesthetics-fitness-club', 'Aesthetics Fitness Club'),
    ('Paphos', 'paphos-professional-boxing-gym', 'Paphos Professional Boxing Gym'),
    ('Paphos', 'poseidonio-health-spa-and-fitness-center', 'Poseidonio Health Spa And Fitness Center'),
    ('Paphos', 'municipality-gym', 'Municipality Gym'),
    ('Paphos', 'aidinidis-fight-club', 'Aidinidis Fight Club'),
    ('Paphos', 'johnnys-gym', 'JohnnyS Gym'),
    ('Paphos', 'fiit-paphos-training-room', 'Fiit Paphos Training Room'),
    ('Paphos', 'nayara-fonseca-aerial', 'Nayara Fonseca Aerial'),
    ('Paphos', 'vo2-fitness-center-personal-training-studio', 'Vo2 Fitness Center - Personal Training Studio'),
    ('Paphos', 'star-fitness-gym-paphos-cyprus', 'Star Fitness Gym Paphos Cyprus'),
    ('Paphos', 'vigour-studio-gym', 'Vigour Studio Gym'),
    ('Paphos', 'aesthetics-fitness-club-gold', 'Aesthetics Fitness Club Gold'),
    ('Paphos', 'bodyart-fitnessgym', 'Bodyart Fitnessgym'),
    ('Paphos', 'energy-fitness-gym', 'Energy Fitness Gym'),
    ('Paphos', 'hardcoretraining-gym-paphos', 'Hardcoretraining Gym Paphos'),
    ('Paphos', 'paphos-thai-boxing-mma-fight-club-old-style-muay-thai', 'Paphos Thai Boxing & Mma Fight Club Old Style Muay Thai'),
    ('Paphos', 'g-fitness', 'G Fitness'),
    ('Paphos', 'west-34-elite-fitness-club', 'West 34 Elite Fitness Club'),
    ('Paphos', 'forma-personal-training-studio-gym', 'Forma Personal Training Studio Gym'),
    ('Paphos', 'gymnastika-fitness-center', 'Gymnastika Fitness Center'),
    ('Paphos', 'hyper-fitness-club', 'Hyper Fitness Club'),
    ('Ayia Napa', 'sunwing-fitness-center', 'Sunwing Fitness Center'),
    ('Ayia Napa', 'overall-magic-fitness-center', 'Overall Magic Fitness Center'),
    ('Ayia Napa', 'datiki-diet', 'Datiki Diet'),
    ('Ayia Napa', 'return-rehabilitation-fitness-recovery-centre', 'Return Rehabilitation & Fitness Recovery Centre'),
    ('Ayia Napa', 'world-gym-ayia-napa', 'World Gym Ayia Napa'),
    ('Ayia Napa', 'bad-dog-bjj-brazilian-jiu-jitsu-training-club-nickbjj', 'Bad Dog Bjj  Brazilian Jiu-Jitsu Training Club  Nickbjj'),
    ('Protaras', 'body-shape-gym', 'Body Shape Gym'),
    ('Protaras', 'bodyart-fitness-center', 'Bodyart Fitness Center'),
    ('Protaras', 'mythical-performance', 'Mythical Performance'),
    ('Protaras', 'demari-wellness-and-spa', 'Demari Wellness And Spa'),
    ('Protaras', 'limitlessxposed', 'Limitlessxposed'),
    ('Protaras', 'sacred-roots-yoga-massage', 'Sacred Roots Yoga & Massage'),
    ('Protaras', 'calisthenicsworkout4allcy', 'Calisthenicsworkout4Allcy')
  ) AS t(city_name, slug, name)
)
SELECT
  e.city_name,
  e.slug,
  e.name as expected_name,
  CASE WHEN g.id IS NULL THEN 'MISSING' ELSE 'EXISTS' END as status
FROM expected_gyms e
LEFT JOIN gyms g ON g.slug = e.slug
LEFT JOIN cities c ON c.id = g.city_id AND c.name = e.city_name
WHERE g.id IS NULL  -- Only show missing
ORDER BY e.city_name, e.slug;
