-- Migration: Insert mock gym data (20 gyms)
-- Date: 2024-01-26
-- This migration inserts all mock gyms with their specialties and amenities

BEGIN;

-- Helper function to get gym ID by slug (for relationships)
CREATE OR REPLACE FUNCTION get_gym_id_by_slug(gym_slug TEXT)
RETURNS UUID AS $$
  SELECT id FROM gyms WHERE slug = gym_slug;
$$ LANGUAGE SQL;

-- Insert all gyms
-- Note: This is a simplified version. Full migration should be generated by script.

-- Example: Powerhouse Gym Limassol
INSERT INTO gyms (
  name, slug, description, address, city_id, latitude, longitude,
  phone, email, website, logo_url, cover_image_url,
  opening_hours, is_featured, rating, review_count, years_in_business,
  member_count, member_count_source, member_count_verified, member_count_public,
  created_at, updated_at
)
VALUES (
  'Powerhouse Gym Limassol',
  'powerhouse-gym-limassol',
  'Powerhouse Gym Limassol is a state-of-the-art fitness facility offering world-class equipment and expert trainers in the heart of Limassol. With over 3,000 square meters of training space, we provide everything you need for your fitness journey. Our comprehensive gym in Limassol features extensive bodybuilding equipment, CrossFit-style functional training areas, and dedicated spaces for strength training. Whether you''re searching for a gym near me in Limassol or looking for the best fitness center in the city, Powerhouse Gym offers 24/7 access, making it perfect for early morning workouts, late-night training, or flexible scheduling. Our certified personal trainers provide one-on-one guidance, and our facility includes modern cardio equipment, free weights, machines, and specialized training zones. Located on Makarios Avenue, we''re easily accessible and offer parking, showers, locker rooms, and a sauna for post-workout relaxation. Join our community of fitness enthusiasts in Limassol and experience why we''re considered one of the top gyms in the city.',
  '123 Makarios Avenue, Limassol 3040',
  'a8d0fd41-5901-4a94-93d3-ecc28166b137', -- Limassol
  34.7071,
  33.0226,
  '+357-25-123456',
  'limassol@powerhousegym.com',
  'https://powerhousegym.com',
  '/images/gyms/powerhouse-limassol-1.jpg',
  '/images/gyms/powerhouse-limassol-1.jpg',
  '{"monday":"6:00 AM - 11:00 PM","tuesday":"6:00 AM - 11:00 PM","wednesday":"6:00 AM - 11:00 PM","thursday":"6:00 AM - 11:00 PM","friday":"6:00 AM - 11:00 PM","saturday":"8:00 AM - 10:00 PM","sunday":"8:00 AM - 10:00 PM"}'::jsonb,
  true,
  4.5,
  127,
  8,
  2500,
  'Demo Data',
  false,
  true,
  '2016-01-15'::timestamptz,
  '2024-01-20'::timestamptz
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  updated_at = EXCLUDED.updated_at;

-- Insert specialties for Powerhouse Gym Limassol
INSERT INTO gym_specialties (gym_id, specialty_id)
SELECT 
  get_gym_id_by_slug('powerhouse-gym-limassol'),
  id
FROM specialties
WHERE slug IN ('bodybuilding', 'crossfit')
ON CONFLICT DO NOTHING;

-- Insert amenities for Powerhouse Gym Limassol
INSERT INTO gym_amenities (gym_id, amenity_id)
SELECT 
  get_gym_id_by_slug('powerhouse-gym-limassol'),
  id
FROM amenities
WHERE slug IN ('parking', 'showers', 'locker-room', 'personal-training', '24-hour-gym', 'sauna')
ON CONFLICT DO NOTHING;

-- Note: This is a template. The full migration should include all 20 gyms.
-- For production, use the migration script to generate the complete SQL.

COMMIT;

-- Clean up helper function
DROP FUNCTION IF EXISTS get_gym_id_by_slug(TEXT);

